server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=STOCK-INTEGRATION;encrypt=true;trustServerCertificate=true
    username: sa
    password: Btk123456
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      write-dates-as-timestamps: false